### ISSUE TITLE
awk statement to filter out rbdiv.$CUTOFFS.out faster than grep

### ISSUE THREAD

**Issue by ericgarciaresearch** [cbirdlab/dDocentHPC#11]
dDocentHPC.bash: line 1347
Replace:
grep -f rbdiv.$CUTOFFS.readsPERprecluster.filtered rbdiv.$CUTOFFS.out > rbdiv.$CUTOFFS.out.filtered
with:
awk -F'\t' 'NR==FNR{c[$5]++;next};c[$5]' rbdiv.$CUTOFFS.readsPERprecluster.filtered rbdiv.$CUTOFFS.out > rbdiv.$CUTOFFS.out.filtered

**Comment by cbird808** [comment]
I made this change, thank you!
