### ISSUE TITLE
Type leading to bug

### ISSUE THREAD

**Issue by jdselwyn** [cbirdlab/dDocentHPC#3]
https://github.com/cbirdlab/dDocentHPC/blob/260603044e7139e56376d6b1845caf93e859402f/dDocentHPC.bash#L1017

In the line linked above (L1017) the first " is in the wrong place. The line should be:
parallel --no-notice -j $NUMProc "pearRM -f {}$Fsed -r {}$Rsed -o {} -j $NUMProc -n $LENGTH -p 0.0001" ::: "${NAMES[@]}"

**Comment by cbird808** [comment]
fixed
