### ISSUE TITLE
Config File issue

### ISSUE THREAD

**Issue by jdselwyn** [cbirdlab/dDocentHPC#4]
This line in the config file:
`no		freebayes -J --pooled-discrete (yes|no)`

Needs to change to this:
`no		freebayes -J --pooled-discrete (yes or no)`

So the parsing of the genotyping properly goes to Individual genotyping not Pools with ploidy 2

**Comment by cbird808** [comment]
I will update dDocentHPC.bash to accept either

**Comment by cbird808** [comment]
I resolved this by dialing back the length of the search patterns for pulling the settings out of the config file. Changes have been pushed to github
